language: node_js

sudo: required

services:
  - docker

jobs:
  include:
    - stage: core
      name: "Code Challenge CORE"
      if: branch = master AND type != pull_request AND fork = false
      script:
        # building support applications image

        - docker build -f ./.support/categories/Dockerfile -t cs-api-categories ./.support/categories
        - docker build -f ./.support/coupons/Dockerfile -t cs-api-coupons ./.support/coupons

        # deploying to Heroku cloud

        - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

        - docker tag api-categories registry.heroku.com/$HEROKU_CATEGORIES_APPLICATION/web
        - docker tag api-coupons registry.heroku.com/$HEROKU_COUPONS_APPLICATION/web

        - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        - docker push registry.heroku.com/$HEROKU_CATEGORIES_APPLICATION/web
        - docker push registry.heroku.com/$HEROKU_COUPONS_APPLICATION/web

        - heroku ps:scale web=1 -a $HEROKU_CATEGORIES_APPLICATION
        - heroku ps:scale web=1 -a $HEROKU_COUPONS_APPLICATION
