language: java

jdk:
  - oraclejdk11

jobs:
  include:
    - stage: validation
      name: "Code Challenge Validation"
      if: type = pull_request AND fork = true
      script:
        - if [ -e build.gradle ]; then ./gradlew check ; fi
        - if [ -e pom.xml ]; then mvn test -B ; fi

notifications:
  slack: vtrsalgado:J4NygsuDQPf4qkIxn2sCG7h3#general
    on_pull_requests: true
